### ISSUE TITLE
Mapa de produtores

### ISSUE THREAD

**Issue by brunorsousa6** [ES-UFABC/Grupo-18-Agricolab#58]
- [x] API para lista de produtores(filtro por nome, latitude e longitude)
- [x] adicionar calculo de informações para o mapa
- [x] front - mapa
- [x] integração de serviços
- [x] deploy

**Comment by anandaantenor** [comment]
@wesleybs90  @brunorsousa6 eu comecei a pesquisar sobre como poderíamos fazer isso e encontrei esses websites. Eu ia tentar começar a fazer, mas admito que me perdi toda. Alguém que fazer um pair programming para tentar começar a primeira tarefa?

https://www.javatips.net/api/cordova-mapbox-android-sdk-master/src/android/com/affinitybridge/cordova/mapbox/MapEditorActivity.java

https://docs.mapbox.com/android/java/examples/

https://docs.mapbox.com/android/java/guides/
